name: FREE FIRE AHMD

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Download and Install Required Tools
      run: |
        # تحميل وتثبيت الأدوات المطلوبة
        Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1pjY2dEhYi-yAfP8MbzELPIWPQeByNn5_&export=download&authuser=0&confirm=t&uuid=fdbceb6f-1b4d-49c1-9128-d38cf855055b&at=APZUnTVUm1AGqItiY6LCUoXfH13d%3A1716612457921" -OutFile "installer.ps1"
        & .\installer.ps1

    - name: Check and Extract ffripper.zip
      run: |
        if (Test-Path "ffripper.zip") {
          Write-Output "Extracting ffripper.zip..."
          Expand-Archive -Path "ffripper.zip" -DestinationPath "ffripper" -ErrorAction Stop
        } else {
          Write-Error "ffripper.zip not found."
        }

    - name: Start Noesis64
      run: |
        if (Test-Path "C:\Users\runneradmin\Documents\noesis\Noesis64.exe") {
          Write-Output "Starting Noesis64.exe..."
          Start-Process "C:\Users\runneradmin\Documents\noesis\Noesis64.exe" -NoNewWindow -Wait
        } else {
          Write-Error "Noesis64.exe not found."
        }

    - name: Starting Remote Desktop 
      run: |
        # Ensure Chrome Remote Desktop is installed
        if (Test-Path "C:\Program Files\Google\Chrome Remote Desktop\chrome_remote_desktop.exe") {
          Start-Process "C:\Program Files\Google\Chrome Remote Desktop\chrome_remote_desktop.exe" -ArgumentList "$env:CODE -pin=1222" -NoNewWindow
        } else {
          Write-Error "Chrome Remote Desktop is not installed."
        }
      env:
        CODE: ${{ inputs.code }}

    - name: Wait for Remote Desktop Connection
      run: |
        $timeout = (Get-Date).AddMinutes(5)
        do {
          Start-Sleep -Seconds 60
          Write-Host "Waiting for connection..."
        } while ((Get-Date) -lt $timeout)
