name: FREE FIRE AHMD

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Downloading And Installing Free Fire And Tools
      run: |
        # تحميل وتثبيت Free Fire والأدوات
        Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1pjY2dEhYi-yAfP8MbzELPIWPQeByNn5_&export=download&authuser=0&confirm=t&uuid=fdbceb6f-1b4d-49c1-9128-d38cf855055b&at=APZUnTVUm1AGqItiY6LCUoXfH13d%3A1716612457921" -OutFile "installer.ps1"
        & .\installer.ps1

    - name: Starting Remote Desktop 
      run: |
        # تأكد من تثبيت Chrome Remote Desktop وتحديثه
        if (Test-Path "C:\Program Files\Google\Chrome Remote Desktop\chrome_remote_desktop.exe") {
          # استخدم الأمر المناسب لتشغيل الاتصال بـ Chrome Remote Desktop
          Start-Process "C:\Program Files\Google\Chrome Remote Desktop\chrome_remote_desktop.exe" -ArgumentList "$env:CODE -pin=1222" -NoNewWindow
        } else {
          Write-Error "Chrome Remote Desktop غير مثبت على النظام."
        }
      env:
        CODE: ${{ inputs.code }}

    - name: Wait for Remote Desktop Connection
      run: |
        # انتظر حتى يتصل Remote Desktop
        $timeout = (Get-Date).AddMinutes(5)
        do {
          Start-Sleep -Seconds 60
          Write-Host "انتظار الاتصال..."
        } while ((Get-Date) -lt $timeout)
