name: FREE FIRE RIPPER

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 60  # Set a more reasonable timeout

    steps:
    - name: Downloading and Installing Free Fire and Tools
      run: |
        # WAIT FOR 3-4 MINUTES 
        Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1pjY2dEhYi-yAfP8MbzELPIWPQeByNn5_&export=download&authuser=0&confirm=t&uuid=fdbceb6f-1b4d-49c1-9128-d38cf855055b&at=APZUnTVUm1AGqItiY6LCUoXfH13d%3A1716612457921" -OutFile "installer.ps1"
        Start-Process powershell -ArgumentList "./installer.ps1" -NoNewWindow -Wait

    - name: Starting Remote Desktop
      run: |
        # Securely handle and use the code
        $code = "${{ secrets.REMOTE_DESKTOP_CODE }}"
        # Replace this line with the actual command to start the remote desktop session
        Start-Process "chrome-remote-desktop" -ArgumentList "--code=$code"

    - name: Keep Remote Desktop Running
      run: |
        # Sleep for 38 days
        Start-Sleep -Seconds 38 * 24 * 60 * 60
